# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18585fd27a34a332b6e033a3db18d74ed9915320fa5d51b90e3a50dd5300fc62b64bfaa2fc47cfad65969b597c3d2bc3716d90552f0cbb68ed4c555a62ed830f

test:
  secret_key_base: 500f4823c07184d99d9e83acb760ff2d42d4dee7e45782517d58be25105a4cf756931a125ba1bc5aaa18134bc4bff39c13e79b27dd7695dc0be9ca681c20b4ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
